### ISSUE TITLE
No syntax highlighting for `@use` 

### ISSUE THREAD

**Issue by CrazyTim** [braver/Sass#69]
I suggest making it simular as `@import`.

**Comment by braver** [comment]
I'm actually really sure we have highlighting for `@use` and `@forward`. Any specific code where you have a problem? With screenshots perhaps?

**Comment by CrazyTim** [comment]
@braver sure, here is sample code and screen shot. I found a few more syntax issues and have included them here.

```scss
@include '../vars';
@use '../vars'; // expect "@use" to be pink, and "'../vars'" to be yellow, like "@include" above.

input {

  order: 1; // expect "order" to be legal.

  align-items: center; // expect "-items" to be blue.

  background-size: cover; // expect "cover" to be blue, like "center" above.

}

input::before {
  content: '';
}

input::placeholder { // expect "placeholder" to be green, like "before" above.
  color: #999;
}
```

![image](https://user-images.githubusercontent.com/8240660/95041109-7c8f1880-0721-11eb-87c9-d05c0b2b0ff6.png)
